version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=10h
      - JWT_REFRESH_EXPIRES_IN=21h
      - PORT=8080
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chat-network

volumes:
  backend_data:
    driver: local

networks:
  chat-network:
    driver: bridge 